//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public int delivery_ID { get; set; }
        public Nullable<int> supplier_ID { get; set; }
        public Nullable<int> part_ID { get; set; }
        public Nullable<System.DateTime> dateDeliveliry { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> unit_Price { get; set; }
    
        public virtual Spare_Parts Spare_Parts { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
