//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Availability
    {
        public int Stock_ID { get; set; }
        public Nullable<int> part_ID { get; set; }
        public Nullable<int> storage_ID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Spare_Parts Spare_Parts { get; set; }
        public virtual Storages Storages { get; set; }
    }
}
